#!/usr/bin/env python3
"""Read-only documentation health checks for AIPocket."""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from urllib.parse import unquote

REPO_ROOT = Path(__file__).resolve().parents[1]
REQUIRED_FRONTMATTER_FIELDS = ("title", "type", "status", "updated", "summary")
REQUIRED_DOC_ENTRIES = (
    "docs/README.md",
    "docs/INDEX.md",
    "docs/DOCUMENTATION.md",
    "docs/DOCS-SPEC.md",
    "docs/architecture.md",
    "dev/README.md",
    "dev/progress/status.md",
    "frontend/README.md",
)
STATUS_MD_PATH = "dev/progress/status.md"
STATUS_MD_MAX_LINES = 200
FRONTMATTER_EXEMPT_FILES = {
    "AGENTS.md",
    "CLAUDE.md",
    "README.md",
}
SKIP_DIR_PARTS = {
    "archive",
    "local",
    ".git",
    "target",
    "node_modules",
    "dist",
    ".worktrees",
}
SKIP_RELATIVE_FILES = {
    "docs/local-deploy.md",
    "dev/progress/status-history-archive.md",
}
LINK_SKIP_PREFIXES = (
    "http://",
    "https://",
    "mailto:",
    "tel:",
    "file:",
    "data:",
)
ROOT_RELATIVE_LINK_PREFIXES = (
    "AGENTS.md",
    "CLAUDE.md",
    "README.md",
    "docs/",
    "dev/",
    "crates/",
    "frontend/",
    "migrations/",
    ".env.example",
)
DOC_LINK_SUFFIXES = {".md", ".markdown", ".html", ".htm"}
AUTOGENERATED_MARKERS = (
    "本文件由脚本自动生成",
    "请勿手动编辑",
    "所有 INDEX.md 由 CI 脚本自动生成",
)
CARGO_MEMBERS_BLOCK_RE = re.compile(
    r"members\s*=\s*\[(.*?)\]",
    re.DOTALL,
)
CARGO_MEMBER_ITEM_RE = re.compile(r'"crates/([^"]+)"')


@dataclass(frozen=True)
class Finding:
    path: str
    message: str


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run read-only docs health checks.")
    parser.add_argument("--strict-frontmatter", action="store_true")
    parser.add_argument("--strict-links", action="store_true")
    parser.add_argument("--max-details", type=int, default=30)
    parser.add_argument("--format", choices=("text", "json"), default="text")
    return parser.parse_args()


def repo_path(path: Path) -> str:
    return path.relative_to(REPO_ROOT).as_posix()


def parse_cargo_crates() -> list[str]:
    text = (REPO_ROOT / "Cargo.toml").read_text(encoding="utf-8")
    match = CARGO_MEMBERS_BLOCK_RE.search(text)
    if not match:
        return []
    return sorted(set(CARGO_MEMBER_ITEM_RE.findall(match.group(1))))


def iter_markdown_files() -> list[Path]:
    crates = set(parse_cargo_crates())
    allowed_exact = {"AGENTS.md", "CLAUDE.md", "README.md"}
    files: list[Path] = []
    for path in REPO_ROOT.rglob("*.md"):
        parts = path.relative_to(REPO_ROOT).parts
        relative = repo_path(path)
        if any(part in SKIP_DIR_PARTS for part in parts):
            continue
        if relative in SKIP_RELATIVE_FILES:
            continue
        if not path.is_file():
            continue
        crate_readme = (
            len(parts) == 3 and parts[0] == "crates" and parts[1] in crates and parts[2] == "README.md"
        )
        crate_docs = (
            len(parts) >= 4 and parts[0] == "crates" and parts[1] in crates and parts[2] == "docs"
        )
        frontend_readme = relative == "frontend/README.md"
        docs_or_dev = parts[0] in {"docs", "dev"}
        root_doc = len(parts) == 1 and relative in allowed_exact
        if crate_readme or crate_docs or frontend_readme or docs_or_dev or root_doc:
            files.append(path)
    return sorted(files)


def check_required_entries() -> list[Finding]:
    findings: list[Finding] = []
    for entry in REQUIRED_DOC_ENTRIES:
        if not (REPO_ROOT / entry).exists():
            findings.append(Finding(entry, "required documentation entry is missing"))
    return findings


def check_status_md_line_limit() -> list[Finding]:
    path = REPO_ROOT / STATUS_MD_PATH
    if not path.exists():
        return []
    line_count = len(path.read_text(encoding="utf-8").splitlines())
    if line_count > STATUS_MD_MAX_LINES:
        return [
            Finding(
                STATUS_MD_PATH,
                f"exceeds {STATUS_MD_MAX_LINES} lines ({line_count}); "
                "move historical detail to dev/progress/status-history-archive.md",
            )
        ]
    return []


def check_crate_readmes(crates: list[str]) -> list[Finding]:
    findings: list[Finding] = []
    for name in crates:
        readme = REPO_ROOT / "crates" / name / "README.md"
        if not readme.exists():
            findings.append(Finding(repo_path(readme), "Cargo workspace crate has no README.md"))
    return findings


def frontmatter_findings(markdown_files: list[Path]) -> list[Finding]:
    findings: list[Finding] = []
    for path in markdown_files:
        if repo_path(path) in FRONTMATTER_EXEMPT_FILES:
            continue
        lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
        if not lines or lines[0].strip() != "---":
            findings.append(Finding(repo_path(path), "missing YAML frontmatter"))
            continue
        try:
            closing = lines[1:].index("---") + 1
        except ValueError:
            findings.append(Finding(repo_path(path), "frontmatter is not closed"))
            continue
        body = "\n".join(lines[1:closing])
        missing = [
            field
            for field in REQUIRED_FRONTMATTER_FIELDS
            if not re.search(rf"^{field}\s*:", body, re.MULTILINE)
        ]
        if missing:
            findings.append(
                Finding(repo_path(path), "frontmatter missing fields: " + ", ".join(missing))
            )
    return findings


def strip_fenced_code(text: str) -> str:
    return re.sub(r"```.*?```", "", text, flags=re.DOTALL)


def strip_inline_code(text: str) -> str:
    return re.sub(r"`[^`\n]*`", "", text)


def normalize_link_target(raw_target: str) -> str:
    target = raw_target.strip()
    if target.startswith("<") and target.endswith(">"):
        target = target[1:-1].strip()
    if " " in target and not target.startswith(("../", "./")):
        target = target.split(" ", 1)[0]
    return unquote(target)


def markdown_link_targets(text: str) -> list[str]:
    targets: list[str] = []
    index = 0
    while index < len(text):
        open_bracket = text.find("[", index)
        if open_bracket == -1:
            break
        close_bracket = text.find("]", open_bracket + 1)
        if close_bracket == -1:
            break
        open_paren = close_bracket + 1
        if open_paren >= len(text) or text[open_paren] != "(":
            index = close_bracket + 1
            continue
        cursor = open_paren + 1
        depth = 1
        while cursor < len(text):
            char = text[cursor]
            if char == "\\":
                cursor += 2
                continue
            if char == "(":
                depth += 1
            elif char == ")":
                depth -= 1
                if depth == 0:
                    targets.append(text[open_paren + 1 : cursor])
                    break
            cursor += 1
        index = cursor + 1
    return targets


def is_local_link(target: str) -> bool:
    lowered = target.lower()
    return bool(target) and not target.startswith("#") and not lowered.startswith(LINK_SKIP_PREFIXES)


def is_documentation_link_target(raw_target: str) -> bool:
    target = normalize_link_target(raw_target)
    path_part = re.sub(r":\d+(?::\d+)?$", "", target.split("#", 1)[0]).rstrip("/")
    if not path_part:
        return False
    name = Path(path_part).name
    if "." not in name:
        return True
    return Path(name).suffix.lower() in DOC_LINK_SUFFIXES


def resolve_link(source: Path, raw_target: str) -> Path | None:
    target = normalize_link_target(raw_target)
    if not is_local_link(target):
        return None
    target_without_anchor = re.sub(r":\d+(?::\d+)?$", "", target.split("#", 1)[0])
    if not target_without_anchor:
        return None
    if target_without_anchor.startswith(ROOT_RELATIVE_LINK_PREFIXES):
        repo_target = (REPO_ROOT / target_without_anchor).resolve()
        if repo_target.exists():
            return repo_target
    return (source.parent / target_without_anchor).resolve()


def link_findings(markdown_files: list[Path]) -> list[Finding]:
    findings: list[Finding] = []
    for path in markdown_files:
        text = strip_inline_code(
            strip_fenced_code(path.read_text(encoding="utf-8", errors="replace"))
        )
        for raw_target in markdown_link_targets(text):
            if not is_documentation_link_target(raw_target):
                continue
            target_path = resolve_link(path, raw_target)
            if target_path is None or target_path.exists():
                continue
            findings.append(Finding(repo_path(path), f"broken local link: {raw_target}"))
    return findings


def autogenerated_marker_findings(markdown_files: list[Path]) -> list[Finding]:
    findings: list[Finding] = []
    for path in markdown_files:
        relative = repo_path(path)
        if relative in {"docs/DOCS-SPEC.md", "docs/DOCUMENTATION.md"}:
            continue
        text = path.read_text(encoding="utf-8", errors="replace")
        for marker in AUTOGENERATED_MARKERS:
            if marker in text:
                findings.append(
                    Finding(relative, f"outdated generated-index marker remains: {marker}")
                )
                break
    return findings


def flatten_groups(groups: dict[str, list[Finding]]) -> list[Finding]:
    findings: list[Finding] = []
    for group_findings in groups.values():
        findings.extend(group_findings)
    return findings


def print_grouped_section(title: str, groups: dict[str, list[Finding]], max_details: int) -> None:
    print(f"{title}: {len(flatten_groups(groups))}")
    for group_name, findings in groups.items():
        print(f"  {group_name}: {len(findings)}")
        for finding in findings[:max_details]:
            print(f"    - {finding.path}: {finding.message}")
        remaining = len(findings) - max_details
        if remaining > 0:
            print(f"    ... {remaining} more")


def main() -> int:
    args = parse_args()
    markdown_files = iter_markdown_files()
    crates = parse_cargo_crates()

    error_groups: dict[str, list[Finding]] = {
        "required_entries": check_required_entries() + check_status_md_line_limit(),
        "crate_readmes": check_crate_readmes(crates),
    }
    warning_groups: dict[str, list[Finding]] = {
        "generated_markers": autogenerated_marker_findings(markdown_files),
    }
    frontmatter = frontmatter_findings(markdown_files)
    links = link_findings(markdown_files)
    if args.strict_frontmatter:
        error_groups["frontmatter"] = frontmatter
    else:
        warning_groups["frontmatter"] = frontmatter
    if args.strict_links:
        error_groups["links"] = links
    else:
        warning_groups["links"] = links

    errors = flatten_groups(error_groups)
    warnings = flatten_groups(warning_groups)
    result = "failed" if errors else ("passed_with_warnings" if warnings else "passed")

    if args.format == "json":
        print(
            json.dumps(
                {
                    "result": result,
                    "markdown_files_checked": len(markdown_files),
                    "cargo_crates": len(crates),
                    "counts": {"errors": len(errors), "warnings": len(warnings)},
                    "errors": {
                        name: [{"path": f.path, "message": f.message} for f in findings]
                        for name, findings in error_groups.items()
                    },
                    "warnings": {
                        name: [{"path": f.path, "message": f.message} for f in findings]
                        for name, findings in warning_groups.items()
                    },
                },
                ensure_ascii=False,
                indent=2,
                sort_keys=True,
            )
        )
    else:
        print("Docs health check")
        print(f"- markdown files checked: {len(markdown_files)}")
        print(f"- cargo crates: {len(crates)}")
        print()
        print_grouped_section("Errors", error_groups, args.max_details)
        print_grouped_section("Warnings", warning_groups, args.max_details)
        print()
        if result == "failed":
            print("Result: failed")
        elif result == "passed_with_warnings":
            print("Result: passed with warnings")
        else:
            print("Result: passed")

    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main())
